import React, { useState } from 'react';
import { CaseItem, CorrelationInsight } from '../types';
import { ExtractedDocumentData } from '../utils/documentAnalyzer';

interface ReportsViewProps {
  cases: CaseItem[];
  documents?: ExtractedDocumentData[];
  insights?: CorrelationInsight[];
}

export const ReportsView: React.FC<ReportsViewProps> = ({
  cases,
  documents = [],
  insights = [],
}) => {
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  // Compute top entities from real cases
  const allSuspects = new Set<string>();
  const allVehicles = new Set<string>();
  const allLocations = new Set<string>();

  cases.forEach((c) => {
    c.linkedSuspects.forEach((s) => allSuspects.add(s));
    c.linkedVehicles.forEach((v) => allVehicles.add(v));
    if (c.location) allLocations.add(c.location);
  });

  const topSuspectList = Array.from(allSuspects);
  const topLocationList = Array.from(allLocations);
  const topVehicleList = Array.from(allVehicles);

  const handleExport = () => {
    // Generate authentic plain-text forensic intelligence dossier
    const reportDate = new Date().toISOString().replace('T', ' ').slice(0, 19);
    let dossier = `================================================================================\n`;
    dossier += `            FEDERAL FORENSIC INTELLIGENCE DOSSIER (CONFIDENTIAL)\n`;
    dossier += `            GENERATED BY AEGIS MULTI-SOURCE INVESTIGATION CORE\n`;
    dossier += `================================================================================\n\n`;
    dossier += `DATE GENERATED: ${reportDate} UTC\n`;
    dossier += `ACTIVE CASES: ${cases.length}\n`;
    dossier += `INGESTED DOCUMENTS ANALYZED: ${documents.length}\n`;
    dossier += `CORRELATION INSIGHTS DISCOVERED: ${insights.length}\n`;
    dossier += `TOTAL IDENTIFIED SUSPECTS: ${topSuspectList.length} (${topSuspectList.join(', ') || 'None'})\n`;
    dossier += `HOTSPOT LOCATIONS: ${topLocationList.join(' | ') || 'None'}\n\n`;

    dossier += `--------------------------------------------------------------------------------\n`;
    dossier += `SECTION 1: SYNTHESIZED CASE FILES\n`;
    dossier += `--------------------------------------------------------------------------------\n\n`;

    cases.forEach((c, idx) => {
      dossier += `[CASE ${idx + 1}] ${c.caseNumber} - ${c.title.toUpperCase()}\n`;
      dossier += `  STATUS: ${c.status} | CONFIDENCE LINK SCORE: ${c.confidenceScore}%\n`;
      dossier += `  DATE OPENED: ${c.dateOpened} | LEAD: ${c.leadInvestigator}\n`;
      dossier += `  LOCATION: ${c.location}\n`;
      dossier += `  NARRATIVE: ${c.summary}\n`;
      dossier += `  LINKED SUSPECTS: ${c.linkedSuspects.join(', ') || 'None'}\n`;
      dossier += `  LINKED PHONE NUMBERS: ${c.linkedPhoneNumbers.join(', ') || 'None'}\n`;
      dossier += `  LINKED FINANCIAL ACCOUNTS: ${c.linkedBankAccounts.join(', ') || 'None'}\n`;
      dossier += `  IDENTIFIED VEHICLES: ${c.linkedVehicles.join(', ') || 'None'}\n\n`;
    });

    dossier += `--------------------------------------------------------------------------------\n`;
    dossier += `SECTION 2: INGESTED SOURCE DOCUMENTS INVENTORY\n`;
    dossier += `--------------------------------------------------------------------------------\n\n`;

    documents.forEach((doc, idx) => {
      dossier += `[DOC ${idx + 1}] ${doc.filename} (${doc.sourceType})\n`;
      dossier += `  SUMMARY: ${doc.summary}\n`;
      dossier += `  CONFIDENCE: ${doc.confidenceScore}%\n\n`;
    });

    dossier += `--------------------------------------------------------------------------------\n`;
    dossier += `SECTION 3: ACTIONABLE RECOMMENDATIONS\n`;
    dossier += `--------------------------------------------------------------------------------\n\n`;
    if (topLocationList.length > 0 && topSuspectList.length > 0) {
      dossier += `1. Execute coordinated federal search warrants for primary nodes: ${topLocationList.slice(0, 2).join(' and ')}.\n`;
      dossier += `2. Intercept and interrogate key subjects of interest: ${topSuspectList.slice(0, 3).join(', ')}.\n`;
      if (topVehicleList.length > 0) {
        dossier += `3. Disseminate ALPR automated alerts for tracked vehicle plates: ${topVehicleList.join(', ')}.\n`;
      }
    } else {
      dossier += `Awaiting further multi-source document ingestion to finalize warrant targets.\n`;
    }

    dossier += `\n================================================================================\n`;
    dossier += `                      END OF CONFIDENTIAL INTELLIGENCE REPORT\n`;
    dossier += `================================================================================\n`;

    const blob = new Blob([dossier], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FORENSIC_DOSSIER_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3500);
  };

  return (
    <div className="flex flex-col w-full p-6 space-y-6 max-w-[1600px] mx-auto select-none">
      <div className="bg-[#0a0a0a] rounded-lg border border-[#1a1a1a] p-5 flex flex-wrap items-center justify-between gap-4 shadow-xl">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-emerald-950/40 border border-emerald-800/40 flex items-center justify-center text-emerald-400">
            <span className="material-symbols-outlined text-[24px]">description</span>
          </div>
          <div>
            <h1 className="text-[18px] font-bold text-[#e0e0e0]">Federal Forensic Case Dossiers & Briefings</h1>
            <p className="text-[12px] text-gray-400">
              Compiled cross-case evidence packages derived directly from analyzed input documents.
            </p>
          </div>
        </div>

        <button
          onClick={handleExport}
          disabled={cases.length === 0}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-[13px] font-bold transition-all shadow-lg cursor-pointer ${
            cases.length === 0
              ? 'bg-gray-800 text-gray-500 cursor-not-allowed'
              : 'bg-blue-600 hover:bg-blue-500 text-white shadow-blue-600/20'
          }`}
        >
          <span className="material-symbols-outlined text-[18px]">download</span>
          <span>{downloadSuccess ? 'Dossier Downloaded!' : 'Export Intelligence Dossier (.txt)'}</span>
        </button>
      </div>

      {cases.length === 0 ? (
        <div className="bg-[#0a0a0a] rounded-lg border border-[#1a1a1a] p-12 text-center space-y-3 shadow-xl">
          <span className="material-symbols-outlined text-gray-600 text-[42px]">text_snippet</span>
          <h3 className="text-base font-bold text-[#e0e0e0]">No Case Reports Available</h3>
          <p className="text-xs text-gray-400 max-w-md mx-auto">
            Ingest investigation files or sample records in Data Collection to automatically generate full executive dossiers.
          </p>
        </div>
      ) : (
        <div className="bg-[#0a0a0a] rounded-lg border border-[#1a1a1a] p-6 shadow-xl space-y-6">
          <div className="border-b border-gray-800 pb-4 flex justify-between items-center">
            <div>
              <span className="text-[10px] font-mono text-gray-500 uppercase">CONFIDENTIAL EXECUTIVE BRIEFING</span>
              <h2 className="text-[18px] font-bold text-[#e0e0e0] mt-0.5">
                Synthesis Report: {cases.length} Cross-Correlated Investigations
              </h2>
            </div>
            <span className="text-[10px] font-mono bg-red-950/40 text-red-400 px-3 py-1 rounded-lg border border-red-800/40 font-bold">
              CLASSIFICATION: TOP SECRET
            </span>
          </div>

          <div className="space-y-4 text-sm text-gray-300 leading-relaxed">
            <p>
              This forensic brief documents the synthesis of <strong>{documents.length} analyzed source documents</strong> (FIRs, CDRs, Financial Records, and CCTV logs) across <strong>{cases.length} active investigations</strong>.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              {cases.map((c) => (
                <div key={c.id} className="bg-[#111] p-4 rounded-lg border border-gray-800 space-y-2">
                  <div className="flex justify-between items-start">
                    <span className="font-mono text-xs font-bold text-blue-400">{c.caseNumber}</span>
                    <span className="text-[10px] font-mono text-emerald-400 font-bold">{c.confidenceScore}% LINK</span>
                  </div>
                  <h4 className="font-bold text-[#e0e0e0] text-sm">{c.title}</h4>
                  <p className="text-xs text-gray-400">{c.summary}</p>
                  <div className="pt-2 border-t border-gray-800/60 text-[11px] font-mono text-gray-400">
                    <strong className="text-gray-300">Suspects:</strong> {c.linkedSuspects.join(', ') || 'Pending identification'}
                  </div>
                  {c.linkedVehicles.length > 0 && (
                    <div className="text-[11px] font-mono text-blue-400">
                      <strong className="text-gray-300">Vehicles:</strong> {c.linkedVehicles.join(', ')}
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="bg-[#111] p-4 rounded-lg border border-gray-800 mt-4">
              <h4 className="font-bold text-[#e0e0e0] text-sm mb-2 flex items-center gap-2">
                <span className="material-symbols-outlined text-emerald-400">gavel</span>
                Primary Recommended Action
              </h4>
              <p className="text-xs text-gray-300 leading-relaxed">
                {topLocationList.length > 0 && topSuspectList.length > 0 ? (
                  <>
                    Issue multi-jurisdictional federal search warrants for <strong>{topLocationList.slice(0, 2).join(' and ')}</strong> based on cross-correlated telemetry linking primary subjects of interest <strong>{topSuspectList.slice(0, 3).join(', ')}</strong>
                    {topVehicleList.length > 0 && (
                      <> and recurring vehicle registration <strong>{topVehicleList[0]}</strong></>
                    )}.
                  </>
                ) : (
                  <>Awaiting further document ingestion to establish primary warrant targets and convergence nodes.</>
                )}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
